version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/passwordcheck
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: |
            python -m venv pass
            . pass/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            . pass/bin/activate
            python -m pytest test/ -vv --cov
workflows:
  version: 2
  build_and_test:
    jobs:
      - build